name:
  deformnet
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - scipy
  - tqdm
  - joblib
  - torchmetrics
  - tensorboard
  - pip
  - pip:
    - git+https://github.com/pvigier/perlin-numpy